name: nftrip
dependencies:
- python==3.7.6
- glib==2.51.0
- pip>=20.0.2
- pip:
  - numpy==1.18.1
  - opencv-python
  - torch==1.10.1
  - torchvision==0.11.2
  - pillow
  - matplotlib
  - jupyterlab
  - boto3
  - imageio
  - pandas
  - rudalle
  - timm