name: nftrip
channels:
  - defaults
  - pytorch
dependencies:
- python==3.7.6
- pip=20.0.2
- anaconda
- imageio
- pandas
- pytorch==1.4.0
- torchvision==0.5.0
- pillow
- matplotlib
- jupyterlab
- boto3
- pip:
  - numpy==1.18.1
  - opencv-python