name: nftrip
dependencies:
- python==3.7.6
- glib==2.51.0
- pip>=20.0.2
- pip:
  - numpy==1.18.1
  - opencv-python
  - torch==1.4.0
  - torchvision==0.5.0
  - pillow
  - matplotlib
  - jupyterlab
  - boto3
  - imageio
  - pandas